client_config_backend: settings
client_config:
  client_id: 1015439932653-o489dhm59le27m3ilvssndcsri2vu5tp.apps.googleusercontent.com

  client_secret: kX0bMBWtjz257RYufW3XpzvC

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
 :+1: 1  
